### ISSUE TITLE
Gazebo has been installed,but this error occur

### ISSUE THREAD

**Issue by yxf010** [agn-7/agn_gazebo#1]
phe@phe:~/ros_source/catkin_ws$ catkin_make
Base path: /home/phe/ros_source/catkin_ws
Source space: /home/phe/ros_source/catkin_ws/src
Build space: /home/phe/ros_source/catkin_ws/build
Devel space: /home/phe/ros_source/catkin_ws/devel
Install space: /home/phe/ros_source/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/phe/ros_source/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/phe/ros_source/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - rslidar (metapackage)
-- ~~  - rslidar_msgs
-- ~~  - my_package
-- ~~  - agn_gazebo
-- ~~  - rslidar_driver
-- ~~  - rslidar_pointcloud
-- ~~  - rslidar_rangeimage
-- ~~  - mbot_gazebo
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'rslidar'
-- ==> add_subdirectory(ros_rslidar_robosense/rslidar)
-- +++ processing catkin package: 'rslidar_msgs'
-- ==> add_subdirectory(ros_rslidar_robosense/rslidar_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- rslidar_msgs: 2 messages, 0 services
-- +++ processing catkin package: 'my_package'
-- ==> add_subdirectory(my_package)
-- +++ processing catkin package: 'agn_gazebo'
-- ==> add_subdirectory(agn_gazebo)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    **gazeboConfig.cmake
    gazebo-config.cmake**

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  agn_gazebo/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'gazebo'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
...........................
**Invoking "make cmake_check_build_system" failed**

phe@phe:~/ros_source/catkin_ws$ **gazebo -version**
**Gazebo multi-robot simulator, version 7.0.0**

Gazebo has been installed,but this error occur。

**Comment by yxf010** [comment]
find_package(catkin REQUIRED COMPONENTS
  gazebo_ros
  geometry_msgs
  roscpp
  rospy
  sensor_msgs
  std_msgs
  visualization_msgs
)
remove gazebo ,it done 
but wheni run roslaunch agn_gazebo static_velodyne.launch,failed 
**ResourceNotFound: velodyne_description**

**Comment by agn-7** [comment]
Yes, that's right, "gazebo" was wrong, but I forgot to push my last changes.

I will update my repo by `velodyne_description` package.

**Comment by agn-7** [comment]
I updated my repo, also you could get the velodyne_simulator packages from [this link](http://wiki.ros.org/velodyne_description).

**Comment by agn-7** [comment]
@yxf010 I updated my repo and its readme, check it out. I hope your problem will solve.
